ERROR_NOT_GM = "Caller must be game master"
ERROR_GAME_IN_PROGRESS = "Game is in progress"
ERROR_GAME_NOT_IN_PROGRESS = "Game not in progress"
ERROR_PLAYER_NOT_ACTIVE = "Player is not active"
ERROR_ONLY_PLAYER_NOT_ACTED = "Player already acted this turn"
ERROR_ONLY_ACTIVE_STRATEGY = "Can only be called by active strategy"
